### ISSUE TITLE
Release v0.1.4 via crates.io

### ISSUE THREAD

**Issue by 0ndorio** [hobofan/cargo-nono#25]
It seems like v0.1.4 was never uploaded to [crates.io](https://crates.io/crates/cargo-nono). If this was by intention feel free to close the issue (even If a short explanation would be great).

**Comment by hobofan** [comment]
Done!

No, not intentional 😅 It's the first release that also exists as prebuilt binaries, and I imagined that most people would use it via that, so I forgot about it.

Thank you very much for pointing it out! 👏
