### ISSUE TITLE
Help message lacks trailing newline

### ISSUE THREAD

**Issue by sunfishcode** [hobofan/cargo-nono#9]
```
$ cargo nono
cargo nono 

USAGE:
    cargo nono [SUBCOMMAND]

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

SUBCOMMANDS:
    check    
    help     Prints this message or the help of the given subcommand(s)$
```
That final `$` is the shell prompt, meaning the last line of output didn't end with a newline.

While here, I also wanted to mention that cargo-nono helped me discover several issues with the no_std support in [Cranelift](https://github.com/CraneStation/cranelift/). Thanks!

**Comment by hobofan** [comment]
Huh, cargo-nono is just using the default functionality of `clap`. But yeah, I guess we can just print a newline manually after that.

> While here, I also wanted to mention that cargo-nono helped me discover several issues with the no_std support in Cranelift. Thanks!

Yay, really glad to hear that! :)

**Comment by hobofan** [comment]
Should be fixed now. Not sure how soon I'll do the next release, though.

In the meantime it can be installed with:
```
cargo install --git https://github.com/hobofan/cargo-nono.git --rev 1dcdc3baeee0e50130730072992ffd555285d80e
```
